version: '3'

services:
  app:
    build: .
    container_name: smart-med-reports
    network_mode: host
    ports:
      - "8000:8000/tcp"
    command: bash -c "cd app && uvicorn main:app"
    env_file:
      - .env
    volumes:
      - ./fastapi_app.db:/fastapi_app.db:delegated
